exports.seed = function(knex, Promise) {
  let players = [
    {
      user_id: 1,
      game_id: 1,
      won: true,
      hit_points: 5000,
      score: 5000,
      shots: 80,
      rnd_multiplier: 5,
    },
    {
      user_id: 1,
      game_id: 2,
      won: true,
      hit_points: 4000,
      score: 5000,
      shots: 80,
      rnd_multiplier: 2,
    },
    {
      user_id: 1,
      game_id: 3,
      won: true,
      hit_points: 3000,
      score: 3000,
      shots: 80,
      rnd_multiplier: 3,
    },
    {
      user_id: 1,
      game_id: 4,
      won: true,
      hit_points: 4000,
      score: 7000,
      shots: 80,
      rnd_multiplier: 4,
    },
    {
      user_id: 1,
      game_id: 5,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 1,
    },
    {
      user_id: 1,
      game_id: 6,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 3,
    },
    {
      user_id: 1,
      game_id: 7,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 2,
    },
    {
      user_id: 1,
      game_id: 8,
      won: true,
      hit_points: 7000,
      score: 7000,
      shots: 80,
      rnd_multiplier: 3,
    },
    {
      user_id: 1,
      game_id: 9,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 2,
    },
    {
      user_id: 1,
      game_id: 10,
      won: true,
      hit_points: 5000,
      score: 5000,
      shots: 80,
      rnd_multiplier: 1,
    },
    {
      user_id: 2,
      game_id: 1,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 5,
    },
    {
      user_id: 2,
      game_id: 2,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 2,
    },
    {
      user_id: 2,
      game_id: 3,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 80,
      rnd_multiplier: 3,
    },
    {
      user_id: 2,
      game_id: 4,
      won: false,
      hit_points: 0,
      score: 0,
      shots: 50,
      rnd_multiplier: 4,
    },
    {
      user_id: 2,
      game_id: 5,
      won: true,
      hit_points: 1000,
      score: 1000,
      shots: 60,
      rnd_multiplier: 3,
    },
    {
      user_id: 2,
      game_id: 6,
      won: true,
      hit_points: 3000,
      score: 6000,
      shots: 0,
      rnd_multiplier: 9,
    },
    {
      user_id: 2,
      game_id: 7,
      won: true,
      hit_points: 5000,
      score: 8000,
      shots: 0,
      rnd_multiplier: 2,
    },
    {
      user_id: 2,
      game_id: 8,
      won: false,
      hit_points: 4000,
      score: 0,
      shots: 0,
      rnd_multiplier: 3,
    },
    {
      user_id: 2,
      game_id: 9,
      won: true,
      hit_points: 3000,
      score: 3000,
      shots: 40,
      rnd_multiplier: 2,
    },
    {
      user_id: 2,
      game_id: 10,
      won: false,
      hit_points: 3000,
      score: 0,
      shots: 0,
      rnd_multiplier: 1,
    },
  ]

  // insert users into users table
  return knex('players').insert(players);
};
